# Build-Phase
FROM node:20-alpine AS build
WORKDIR /app

# Kopiere package.json und installiere Abhängigkeiten
COPY package*.json ./
RUN npm install

# Kopiere den Quellcode und baue die Anwendung
COPY . .
RUN npm run build

# Deployment-Phase
FROM nginx:alpine
# Kopiere die gebauten Dateien aus der Build-Phase
COPY --from=build /app/dist/oauth2-open-idconnect-angular-frontend-jee-backend/browser /usr/share/nginx/html
# Kopiere die angepasste Nginx-Konfiguration
COPY nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
