services:
  # JEE Backend
  backend:
    build:
      context: ./jeebackend
      dockerfile: Dockerfile.backend
    container_name: windows-auth-backend
    ports:
      - "8080:8080"
      - "9990:9990" # Admin console
    environment:
      # LDAP Configuration
      - LDAP_URL=ldap://openldap:389
      - LDAP_BASE_DN=dc=example,dc=com
      - LDAP_BIND_DN=cn=ServiceAccount,ou=Users,dc=example,dc=com
      - LDAP_PASSWORD=servicepassword
      # Test mode for local development
      - AUTH_TEST_MODE=true
      - AUTH_TEST_SIMULATED_USER=jdoe
    volumes:
      - ./jeebackend/target:/opt/jboss/wildfly/standalone/deployments
    networks:
      - auth-network
    depends_on:
      - openldap

  # Angular Frontend
  frontend:
    build:
      context: ./angular-frontend
      dockerfile: Dockerfile.frontend
    container_name: windows-auth-frontend
    ports:
      - "80:80"
    networks:
      - auth-network
    depends_on:
      - backend

  # OpenLDAP Server
  openldap:
    image: osixia/openldap:1.5.0
    container_name: openldap
    env_file:
      - ./ldap-test/config/ldap.env
    ports:
      - "389:389"
      - "636:636"
    volumes:
      - ./ldap-test/bootstrap:/container/service/slapd/assets/config/bootstrap/ldif/custom
      - ldap-data:/var/lib/ldap
      - ldap-config:/etc/ldap/slapd.d
    networks:
      - auth-network

  # LDAP Admin UI
  phpldapadmin:
    image: osixia/phpldapadmin:0.9.0
    container_name: phpldapadmin
    environment:
      PHPLDAPADMIN_LDAP_HOSTS: "openldap"
      PHPLDAPADMIN_HTTPS: "false"
    ports:
      - "8081:80"
    depends_on:
      - openldap
    networks:
      - auth-network

volumes:
  ldap-data:
  ldap-config:

networks:
  auth-network:
    driver: bridge
