# Build stage
FROM maven:3.8-openjdk-17 AS build
WORKDIR /app
COPY pom.xml .
# Download dependencies in a separate layer for better caching
RUN mvn dependency:go-offline
COPY src ./src
RUN mvn package

# Runtime stage
FROM payara/micro:5.2022.5-jdk17
WORKDIR /opt/payara

# Copy the war file from the build stage
COPY --from=build /app/target/*.war /opt/payara/deployments/

# Set environment variables for MP JWT Auth
ENV MP_JWT_VERIFY_PUBLICKEY_LOCATION=http://keycloak:8080/realms/PoCRealm%20Oauth2OpenIdConnect/protocol/openid-connect/certs
ENV MP_JWT_VERIFY_ISSUER=http://keycloak:8080/realms/PoCRealm%20Oauth2OpenIdConnect
ENV MP_JWT_VERIFY_AUDIENCES=angular-client

# Expose the port for the application
EXPOSE 8080
EXPOSE 9080

# Command to run the application
CMD ["--deploymentDir", "/opt/payara/deployments", "--port", "9080"]